package codigo;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aleja
 */
public class Formulario extends javax.swing.JFrame {
    
    DOM gesDOM = new DOM();

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMensaje = new javax.swing.JLabel();
        jButtonMostrarDOM = new javax.swing.JButton();
        jButtonMostrarSAX = new javax.swing.JButton();
        jButtonMostrarJAXB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSalida = new javax.swing.JTextArea();
        jLabelTitulo = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jLabelAutor = new javax.swing.JLabel();
        jTextFieldAutor = new javax.swing.JTextField();
        jLabelAnno = new javax.swing.JLabel();
        jTextFieldAnno = new javax.swing.JTextField();
        jBtnAnnadir = new javax.swing.JButton();
        jBtnGuardarDOM = new javax.swing.JButton();
        jLabelTituloAntiguo = new javax.swing.JLabel();
        jTextFieldTituloAntiguo = new javax.swing.JTextField();
        jLabelTituloNuevo = new javax.swing.JLabel();
        jTextFieldTituloNuevo = new javax.swing.JTextField();
        jLabelAutorAntiguo = new javax.swing.JLabel();
        jTextFielldAutorAntiguo = new javax.swing.JTextField();
        jLabelAutorNuevo = new javax.swing.JLabel();
        jTextFieldAutorNuevo = new javax.swing.JTextField();
        jLabelAnnoAntiguo = new javax.swing.JLabel();
        jTextFieldAnnoAntiguo = new javax.swing.JTextField();
        jLabelAnnoNuevo = new javax.swing.JLabel();
        jTextFieldAnnoNuevo = new javax.swing.JTextField();
        jBtnModificar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemAbrirDOM = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelMensaje.setText("< Fichero XML no seleccionado >");

        jButtonMostrarDOM.setText("Mostrar contenido DOM");
        jButtonMostrarDOM.setEnabled(false);
        jButtonMostrarDOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarDOMActionPerformed(evt);
            }
        });

        jButtonMostrarSAX.setText("Mostrar contenido SAX");
        jButtonMostrarSAX.setEnabled(false);
        jButtonMostrarSAX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarSAXActionPerformed(evt);
            }
        });

        jButtonMostrarJAXB.setText("Mostrar contenido JAXB");
        jButtonMostrarJAXB.setEnabled(false);
        jButtonMostrarJAXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarJAXBActionPerformed(evt);
            }
        });

        jTextAreaSalida.setColumns(20);
        jTextAreaSalida.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSalida);

        jLabelTitulo.setText("Título");

        jLabelAutor.setText("Autor");

        jLabelAnno.setText("Publicado en");

        jBtnAnnadir.setText("Añadir");
        jBtnAnnadir.setEnabled(false);
        jBtnAnnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAnnadirActionPerformed(evt);
            }
        });

        jBtnGuardarDOM.setText("Guardar DOM como salida XML");
        jBtnGuardarDOM.setEnabled(false);
        jBtnGuardarDOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarDOMActionPerformed(evt);
            }
        });

        jLabelTituloAntiguo.setText("Título antiguo");

        jLabelTituloNuevo.setText("Título nuevo");

        jLabelAutorAntiguo.setText("Autor antiguo");

        jLabelAutorNuevo.setText("Autor nuevo");

        jLabelAnnoAntiguo.setText("Publicado en antiguo");

        jLabelAnnoNuevo.setText("Publicado en antiguo");

        jBtnModificar.setText("Modificar");
        jBtnModificar.setEnabled(false);
        jBtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnModificarActionPerformed(evt);
            }
        });

        jMenu1.setText("Ficheros XML");

        jMenuItemAbrirDOM.setText("Abrir DOM");
        jMenuItemAbrirDOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAbrirDOMActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAbrirDOM);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonMostrarDOM, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMostrarSAX, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMostrarJAXB, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelAutor, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelTitulo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTitulo)
                                    .addComponent(jTextFieldAutor)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabelAnno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAnno))
                            .addComponent(jBtnGuardarDOM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTituloAntiguo)
                                    .addComponent(jLabelTituloNuevo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTituloNuevo)
                                    .addComponent(jTextFieldTituloAntiguo)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelAutorNuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldAutorNuevo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelAutorAntiguo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFielldAutorAntiguo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelAnnoAntiguo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAnnoAntiguo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelAnnoNuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAnnoNuevo))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(jBtnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addComponent(jBtnAnnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMostrarDOM)
                    .addComponent(jButtonMostrarSAX)
                    .addComponent(jButtonMostrarJAXB))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTitulo)
                            .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAutor)
                            .addComponent(jTextFieldAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAnno)
                            .addComponent(jTextFieldAnno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnAnnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnGuardarDOM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTituloAntiguo)
                            .addComponent(jTextFieldTituloAntiguo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTituloNuevo)
                            .addComponent(jTextFieldTituloNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAutorAntiguo)
                            .addComponent(jTextFielldAutorAntiguo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAutorNuevo)
                            .addComponent(jTextFieldAutorNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAnnoAntiguo)
                            .addComponent(jTextFieldAnnoAntiguo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAnnoNuevo)
                            .addComponent(jTextFieldAnnoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAbrirDOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAbrirDOMActionPerformed
        
        File ficheroXML = null;
        ficheroXML = dialogoSeleccionarFichero();
            
        if(ficheroXML == null){
            this.jLabelMensaje.setText("Fichero no seleccionado.");
        } else {
            if(gesDOM.abrir_XML_DOM(ficheroXML)==-1){
                this.jLabelMensaje.setText("Error al crear el objeto DOM.");
                this.jButtonMostrarDOM.setEnabled(false);
                this.jBtnAnnadir.setEnabled(false);
                this.jBtnGuardarDOM.setEnabled(false);
                this.jBtnModificar.setEnabled(false);
            } else {
                this.jLabelMensaje.setText("¡Objeto DOM creado!");
                this.jButtonMostrarDOM.setEnabled(true);
                this.jBtnAnnadir.setEnabled(true);
                this.jBtnGuardarDOM.setEnabled(true);
                this.jBtnModificar.setEnabled(true);
            }
        }
        
    }//GEN-LAST:event_jMenuItemAbrirDOMActionPerformed

    private void jButtonMostrarDOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarDOMActionPerformed
        
        jTextAreaSalida.setText(gesDOM.recorrer_DOM_y_mostrar());
        
    }//GEN-LAST:event_jButtonMostrarDOMActionPerformed

    private void jButtonMostrarSAXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarSAXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMostrarSAXActionPerformed

    private void jButtonMostrarJAXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarJAXBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMostrarJAXBActionPerformed

    private void jBtnAnnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAnnadirActionPerformed
        
        if (gesDOM.annadirDom(this.jTextFieldTitulo.getText(), this.jTextFieldAutor.getText(), this.jTextFieldAnno.getText()) == -1){
            this.jLabelMensaje.setText("Error al añadir el nodo");
        } else {
            this.jLabelMensaje.setText("Nodo añadido correctamente.");
        }
        
    }//GEN-LAST:event_jBtnAnnadirActionPerformed

    private void jBtnGuardarDOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarDOMActionPerformed
        
        if(gesDOM.guardar_DOM_como_fichero(dialogoGuardarFichero()) == -1){
            this.jLabelMensaje.setText("Error al guardar el fichero.");
        } else {
            this.jLabelMensaje.setText("Fichero guardado correctamente.");
        }
        
    }//GEN-LAST:event_jBtnGuardarDOMActionPerformed

    private void jBtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModificarActionPerformed

        String[] textoAModificar = {jTextFieldTituloAntiguo.getText(), jTextFieldTituloNuevo.getText(), 
                                    jTextFielldAutorAntiguo.getText(), jTextFieldAutorNuevo.getText(), 
                                    jTextFieldAnnoAntiguo.getText(), jTextFieldAnnoNuevo.getText()};
        
        if(gesDOM.modificar_DOM(textoAModificar) == -1){
            this.jLabelMensaje.setText("Error al modificar el fichero.");
        } else {
            this.jLabelMensaje.setText("Fichero modificado correctamente.");
        } 
        
    }//GEN-LAST:event_jBtnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAnnadir;
    private javax.swing.JButton jBtnGuardarDOM;
    private javax.swing.JButton jBtnModificar;
    private javax.swing.JButton jButtonMostrarDOM;
    private javax.swing.JButton jButtonMostrarJAXB;
    private javax.swing.JButton jButtonMostrarSAX;
    private javax.swing.JLabel jLabelAnno;
    private javax.swing.JLabel jLabelAnnoAntiguo;
    private javax.swing.JLabel jLabelAnnoNuevo;
    private javax.swing.JLabel jLabelAutor;
    private javax.swing.JLabel jLabelAutorAntiguo;
    private javax.swing.JLabel jLabelAutorNuevo;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTituloAntiguo;
    private javax.swing.JLabel jLabelTituloNuevo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAbrirDOM;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaSalida;
    private javax.swing.JTextField jTextFieldAnno;
    private javax.swing.JTextField jTextFieldAnnoAntiguo;
    private javax.swing.JTextField jTextFieldAnnoNuevo;
    private javax.swing.JTextField jTextFieldAutor;
    private javax.swing.JTextField jTextFieldAutorNuevo;
    private javax.swing.JTextField jTextFieldTitulo;
    private javax.swing.JTextField jTextFieldTituloAntiguo;
    private javax.swing.JTextField jTextFieldTituloNuevo;
    private javax.swing.JTextField jTextFielldAutorAntiguo;
    // End of variables declaration//GEN-END:variables

    private File dialogoSeleccionarFichero() {
        
        File fichero = null;
        
        try {
            JFileChooser fco = new JFileChooser();

            //Busca evitar abrir ficheros binarios
            fco.setFileFilter(new FileNameExtensionFilter("Archivos xml", "xml"));

            fco.setMultiSelectionEnabled(false);
            fco.setDialogType(JFileChooser.OPEN_DIALOG);

            //Si no se produce ningún error seleccion será 0
            int seleccion = fco.showOpenDialog(this);
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                fichero = fco.getSelectedFile();
                String nombre = fichero.getName();
                String extension = nombre.substring(nombre.lastIndexOf('.') + 1, nombre.length());

                if (!extension.equalsIgnoreCase("xml")) {
                    
                    JOptionPane.showConfirmDialog(null, "Estensión seleccionada no válida.", "", JOptionPane.PLAIN_MESSAGE);
                
                } else {
                    return fichero;
                }
            }
        } catch (Exception ex) {
            System.out.println("Fichero no seleccionado.");
        }

        return null;
    }
    
    private File dialogoGuardarFichero() {
        
        File fichero = null;
        
        try {
            JFileChooser fcs = new JFileChooser();

            //Busca evitar abrir ficheros binarios
            fcs.setFileFilter(new FileNameExtensionFilter("Archivos xml", "xml"));

            fcs.setMultiSelectionEnabled(false);
            fcs.setDialogType(JFileChooser.SAVE_DIALOG);

            //Si no se produce ningún error seleccion será 0
            int seleccion = fcs.showSaveDialog(this);
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                fichero = fcs.getSelectedFile();
                String nombre = fichero.getName();
                String extension = nombre.substring(nombre.lastIndexOf('.') + 1, nombre.length());

                if (!extension.equalsIgnoreCase("xml")) {
                    
                    JOptionPane.showConfirmDialog(null, "Estensión seleccionada no válida.", "", JOptionPane.PLAIN_MESSAGE);
                
                } else {
                    return fichero;
                }
            }
        } catch (Exception ex) {
            System.out.println("Fichero no guardado.");
        }

        return null;
    }
}
